name: Perfect Balance Hoof Care
favicon: null
layout_spectrum: 1
typography_spectrum: 0.34393
title: 'Balance, Performance, Soundness'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e4ebf5'
    - '#18181a'
    - '#cab099'
    - '#474745'
    - '#85827d'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
