name: Perfect Balance Hoof Care
favicon: null
layout_spectrum: 0.14481604611501098
typography_spectrum: 0.05505603435449302
title: 'Balance, Performance, Soundness'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a1819'
    - '#acacb4'
    - '#635b4e'
    - '#ffffff'
    - '#c62e71'
  brandStrength: 0.6875
  lightness: 0.2428388544358313
  saturation: 0.5
  rhythmicContrast: 0.9288764484226704
purpose: []
